### ISSUE TITLE
How does the torrent downloading to mp4 work?

### ISSUE THREAD

**Issue by Tetous** [Enime-Project/enime#1]
## Summary
I was wondering how you were able to have the torrent sites takes anime from them then add them to your site? 
also the site does not work. If you are able to help that would be nice.

**Comment by NADESHIKON** [comment]
Hi.
First of all, I believe this app is a desktop application instead of a site. Second, this application is still in the development stage which I do not expect to have any release publicly available and hence you can't use it. 

However, if you're interested in the torrent part we use [torrent-stream](https://github.com/mafintosh/torrent-stream) to play torrent files without downloading them.

**Comment by AqilCont** [comment]
Thanks for asking, for further questions and other stuff not related to bugs or codebase, please use GitHub Discussions!
Hope this helped you in some way :D
